#Docker Networks
networks:
  asa-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
    attachable: true

services:
  dns:
    build: 
      context: ./DNS
      dockerfile: Dockerfile
    container_name: DNS
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      asa-network:
        ipv4_address: 172.25.0.2

  mail:
    build: 
      context: ./mail
      dockerfile: Dockerfile
    container_name: mail
    ports:
      - "25:25/tcp"
      - "143:143/tcp"
    networks:
      asa-network:
        ipv4_address: 172.25.0.3
  roundcube:
    build: ./roundcube
    container_name: roundcube
    ports:
      - "80:80"
    volumes:
      - roundcube_data:/var/www/html
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=imap://mail
      - ROUNDCUBEMAIL_SMTP_SERVER=smtp://mail
    depends_on:
      - mail
    networks:
      asa-network:
        ipv4_address: 172.25.0.4
  db:
    image: mariadb
    container_name: maildb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: roundcube
      MYSQL_USER: roundcube
      MYSQL_PASSWORD: roundcube
    volumes:
      - ./roundcube/mysql_data:/var/lib/mysql
    networks:
      asa-network:
        ipv4_address: 172.25.0.5

volumes:
  roundcube_data:
  db_data:

