#Docker Networks
networks:
  asa-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
    attachable: true

services:
  dns:
    build: 
      context: ./DNS
      dockerfile: Dockerfile
    container_name: DNS
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      asa-network:
        ipv4_address: 172.25.0.2

  postfix:
    build: 
      context: ./mail/postfix
      dockerfile: Dockerfile
    container_name: postfix
    ports:
      - "25:25/tcp"
    networks:
      asa-network:
        ipv4_address: 172.25.0.3